# Site settings
title: undefined
header-img: img/home-bg.jpg
email: czjchn@163.com
copyright_name: chenzhongjie
description: "记录东西"
baseurl: "/blog"
url: "https://github.com/zhongjie-chen"
#twitter_username: twitter_username
github_username:  zhongjie-chen
facebook_username:  facebook_username
email_username:  czjchn@163.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
